FROM arm32v6/golang:1.11-alpine3.8

LABEL maintainer="Philip Laine <philip.laine@gmail.com>"
LABEL url="https://www.github.com/phillebaba/test-web-server"

ENV ARCH=arm

COPY test-web-server-${ARCH} /opt/bin/test-web-server

ENTRYPOINT ["/opt/bin/test-web-server"]
