---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: status-app
  name: coffee
spec:
  replicas: 2
  selector:
    matchLabels:
      app: coffee
  template:
    metadata:
      labels:
        app: coffee
    spec:
      containers:
      - name: coffee
        image: phillebaba/test-web-server:0.1.0-alpha-linux-arm
